baseURL: "https://www.osoappliance.com"
languageCode: en-us
title: OSO Appliance
theme: PaperMod

params:

  defaultTheme: light
  disableThemeToggle: true

  homeInfoParams:
      Title: OSO Appliance - all things appliances.
      Content: Welcome to the most comprehensive blog about appliances on the internet.
      
  socialIcons:
  Name: facebook
  Url: “https://facebook.com/”
  Name: twitter
  Url: “https://twitter.com/”

  cover: 
      linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true




menu: 
  main: 
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10

    - identifier: overviews
      name: Appliances
      url: /pages/appliance-overview/
      weight: 20

    - identifier: rental
      name: Appliance Rental
      url: /pages/appliance-rental/
      weight: 30

    - identifier: parts
      name: Appliance Parts
      url: /pages/appliance-parts-suppliers/
      weight: 40

    - identifier: repairs
      name: Appliance Repairs
      url: /pages/appliance-repair-technicians/
      weight: 50

    - identifier: forums
      name: Appliance Forums
      url: /pages/forum/
      weight: 60

    - identifier: contact
      name: Contact
      url: /contact
      weight: 70



markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      linkify: false