baseURL: "https://www.osoappliance.com"
languageCode: en-us
title: OSO Appliance
theme: PaperMod

params:

  homeInfoParams:
      Title: OSO Appliance - all things appliances
      Content: Welcome to the most comprehensive blog about appliances on the internet.
      
  socialIcons:
  Name: facebook
  Url: “https://facebook.com/”
  Name: twitter
  Url: “https://twitter.com/”

  cover: 
      linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true


menu: 
  main: 
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10

    - identifier: tags
      name: Tags
      url: /tags
      weight: 20

    - identifier: parts
      name: Appliance Parts Suppliers
      url: /pages/appliance-parts-suppliers
      weight: 30

    - identifier: repairs
      name: Appliance Repair Technicians
      url: /pages/appliance-repair-technicians/
      weight: 40

    - identifier: contact
      name: Contact
      url: /contact
      weight: 50
